// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `main_integration_bitcore`, `new`, `test_main`
// These types are ignored because they are not used by any `pub` functions: `TerminalRunner`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TerminalController>>
abstract class TerminalController implements RustOpaqueInterface {
  Stream<String> createStream();

  void endStream();

  factory TerminalController({required int threadId}) => RustLib.instance.api
      .crateApiControllerTerminalControllerNew(threadId: threadId);

  void push({required String data});
}
