// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_new_thread_id`, `new`, `test_msg`
// These types are ignored because they are not used by any `pub` functions: `ThreadController`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Controller>>
abstract class Controller implements RustOpaqueInterface {
  Stream<String> createStream();

  int getLatestThreadCreated();

  factory Controller() =>
      RustLib.instance.api.crateApiControllerControllerNew();

  void push({required int threadId, required String data});
}
