// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `main`

Future<List<SerialPortInfo>> listAvailablePorts() =>
    RustLib.instance.api.crateApiSerialListAvailablePorts();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< SerialPortInfo>>
abstract class SerialPortInfo implements RustOpaqueInterface {}
